syncro_index:
    path:     /
    defaults: { _controller: "LilWorksStoreBundle:Syncro:index" }
    methods:  GET

syncro_action:
    path:     /action/{what}
    defaults: { _controller: "LilWorksStoreBundle:Syncro:action" }
    methods:  GET


syncro_cleanentityfolder:
    path:     /cleanentityfolder
    defaults: { _controller: "LilWorksStoreBundle:Syncro:cleanEntityFolder" }
    methods:  GET
syncro_cleantag:
    path:     /cleantag
    defaults: { _controller: "LilWorksStoreBundle:Syncro:cleanTag" }
    methods:  GET

syncro_stock:
    path:     /stock
    defaults: { _controller: "LilWorksStoreBundle:Syncro:stock" }
    methods:  GET
syncro_brand:
    path:     /brand
    defaults: { _controller: "LilWorksStoreBundle:Syncro:brand" }
    methods:  GET

syncro_category:
    path:     /category
    defaults: { _controller: "LilWorksStoreBundle:Syncro:category" }
    methods:  GET
syncro_supercategory:
    path:     /supercategory
    defaults: { _controller: "LilWorksStoreBundle:Syncro:supercategory" }
    methods:  GET

syncro_onlinedestocking:
    path:     /onlinedestocking
    defaults: { _controller: "LilWorksStoreBundle:Syncro:onlinedestocking" }
    methods:  GET
syncro_annonce:
    path:     /annonce
    defaults: { _controller: "LilWorksStoreBundle:Syncro:annonce" }
    methods:  GET
syncro_product:
    path:     /product
    defaults: { _controller: "LilWorksStoreBundle:Syncro:product" }
    methods:  GET
syncro_user:
    path:     /user
    defaults: { _controller: "LilWorksStoreBundle:Syncro:user" }
    methods:  GET
syncro_customer:
    path:     /customer
    defaults: { _controller: "LilWorksStoreBundle:Syncro:customer" }
    methods:  GET
syncro_text:
    path:     /text
    defaults: { _controller: "LilWorksStoreBundle:Syncro:text" }
    methods:  GET
syncro_all:
    path:     /all
    defaults: { _controller: "LilWorksStoreBundle:Syncro:all" }
    methods:  GET

