warranty_index:
    path:     /
    defaults: { _controller: "LilWorksStoreBundle:Warranty:index" }
    methods:  GET

warranty_show:
    path:     /{warranty_id}/show
    defaults: { _controller: "LilWorksStoreBundle:Warranty:show" }
    methods:  GET

warranty_new:
    path:     /new
    defaults: { _controller: "LilWorksStoreBundle:Warranty:new" }
    methods:  [GET, POST]

warranty_edit:
    path:     /{warranty_id}/edit
    defaults: { _controller: "LilWorksStoreBundle:Warranty:edit" }
    methods:  [GET, POST]

warranty_delete:
    path:     /{warranty_id}/delete
    defaults: { _controller: "LilWorksStoreBundle:Warranty:delete" }
    methods:  DELETE
